name: build and push Node.js Docker Image 

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Login to Azure Container Registry
        run: |
          az login --service-principal -u ${{ secrets.AZURE_SERVICE_PRINCIPAL_ID }} -p ${{ secrets.AZURE_SERVICE_PRINCIPAL_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          az acr login --name acrfornode
        env:
          AZURE_SERVICE_PRINCIPAL_ID: ${{ secrets.AZURE_SERVICE_PRINCIPAL_ID }}
          AZURE_SERVICE_PRINCIPAL_SECRET: ${{ secrets.AZURE_SERVICE_PRINCIPAL_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      - name: Build and tag Docker image
        run: |
          docker build -t acrfornode.azurecr.io/nodeapp2:latest .
        working-directory: ./

      - name: Push Docker image to Azure Container Registry
        run: |
          docker push acrfornode.azurecr.io/nodeapp2:latest
        working-directory: ./
      - name: Create Azure Container App
        run: |
         az containerapp create --name containerforazure2 --image acrfornode.azurecr.io/nodeapp2:latest
         env:
          AZURE_CONTAINERAPP_KEY: ${{ secrets.AZURE_CONTAINERAPP_KEY }}

     
        

