name: Push to Azure Container Registry
on:
  push:
    branches:
      - master
jobs:
  push-to-azure-container-registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - run: npm ci
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_REGISTRY_NAME }}
          username: ${{ secrets.AZURE_USERNAME }}
          password: ${{ secrets.AZURE_PASSWORD }}
      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
            login-server: ${{ secrets.ACR_REGISTRY_NAME }}
            username: ${{ secrets.AZURE_USERNAME }}
            password: ${{ secrets.AZURE_PASSWORD }}
      - run: |
            docker build . -t ${{ secrets.ACR_REGISTRY_NAME }}/nodeapp:${{ github.sha }}
            docker push ${{ secrets.ACR_REGISTRY_NAME }}/nodeapp:${{ github.sha }}
      - name: Deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          acrName: acrfornodejsapp
          containerAppName: nodeappcontainer
          resourceGroup: ACRforNODEJSapp-RG
          imageToDeploy:  acrfornodejsapp.azurecr.io/nodeapp:${{ github.sha }}

