name: Push to Azure Container Registry
on:
  push:
    branches:
      - master
jobs:
  push-to-azure-container-registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - run: npm ci
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.AZURE_USERNAME }}
          password: ${{ secrets.AZURE_PASSWORD }}
      - name: Build and push Docker image
      - run: docker build .
      - run: docker push ${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io
      #- name: docker push 
       # uses: azure/docker-login@v1
      #  with:
       #   login-server: ${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io
       #   username: ${{ secrets.AZURE_USERNAME }}
     #     password: ${{ secrets.AZURE_PASSWORD }}
                 
